#collection of buckets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  #take a look of all created pods with the name posts
  selector:
    matchLabels:
      app: posts
  #exact configuration of the pod to create
  template:
    metadata:
      labels:
        #kind of css classes
        app: posts
    #pod configuration
    spec:
      containers:
      - name: posts
        image: fanmixco/posts:latest
        #imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000