apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
  - name: posts
  #no version means = docker hub by default
    image: fanmixco/posts:0.0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"